name: build-vue-admin-image

on:
  workflow_dispatch:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]"
        
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d_%H-%M')"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configuare env
        working-directory: ./Sixpence.UI/vue-admin
        run: |
          cat > .env.prod << eof
          NODE_ENV=production
          VITE_APP_INDEX_URL=${{ secrets.VITE_APP_INDEX_URL }}
          VITE_APP_AXIOS_BASE_URL=${{ secrets.VITE_APP_AXIOS_BASE_URL }}
          VITE_APP_TITLE=${{ secrets.VITE_APP_TITLE }}
          eof
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./Sixpence.UI/vue-admin
          file: ./Sixpence.UI/vue-admin/Dockerfile
          # 所需要的体系结构，可以在 Available platforms 步骤中获取所有的可用架构
          platforms: linux/amd64
          # 镜像推送时间
          push: true
          # 给清单打上多个标签
          tags: |
            carldu/tj-vue-admin:latest
            carldu/tj-vue-admin:1.0.0
